
import java.applet.*;
import java.awt.*;

public class DoğruÇizimi extends Applet {

    int width, height;

    public void init() {
        width = getSize().width;  //applet'in genişliği (pixel cinsinden)
        height = getSize().height; //applet'in yüksekliği (pixel cinsinden)
        setBackground(Color.black);

    }

    public void paint(Graphics g) {
        g.setColor(Color.green);
        for (int i = 0; i < 10; ++i) {
            g.drawLine(width, height, i * width / 10, 0);
        }
    }
}


    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
